name       : kraft
version    : '0.97'
release    : 5
source     :
    - https://github.com/dragotin/kraft/archive/refs/tags/v0.97.tar.gz : 9d16c259e2eb44adfcc0682b0e9a09ad5c9dd249db16f3f56c1fee9236fe9af5
license    : GPL-2.0-or-later
component  : office.finance
summary    : Kraft helps to handle your daily quotes and invoices in your small business.
homepage   : http://volle-kraft-voraus.de
description: |
    Kraft is a Qt/KF5 based desktop software with a strong focus on ease of use and the just enough feature set for the use case.
    With Kraft, writing documents like quotes and invoices is very easy and fast. Repeating tasks are supported, documents can be generated semi automatically, ie. invoices from offers sent out before.
builddeps  :
    - pkgconfig(libctemplate)
    - pkgconfig(sqlite3)
    - pkgconfig(Qt5Core)
    - akonadi-contacts-devel
    - extra-cmake-modules
    - grantlee-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
rundeps    :
    - python-pypdf2
    - python-reportlab
    - python-six
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
