name       : kraft
version    : '1.0'
release    : 9
source     :
    - https://github.com/dragotin/kraft/archive/refs/tags/v1.0.tar.gz : b122c5e2be40c76016bc809596779bb156d94ef10d4279cc24c33d598b5e06e4
license    : GPL-2.0-or-later
component  : office.finance
summary    : Kraft helps to handle your daily quotes and invoices in your small business.
homepage   : http://volle-kraft-voraus.de
description: |
    Kraft is a Qt/KF5 based desktop software with a strong focus on ease of use and the just enough feature set for the use case.
    With Kraft, writing documents like quotes and invoices is very easy and fast. Repeating tasks are supported, documents can be generated semi automatically, ie. invoices from offers sent out before.
builddeps  :
    - pkgconfig(libctemplate)
    - pkgconfig(sqlite3)
    - pkgconfig(Qt5Svg)
    - akonadi-contacts-devel
    - extra-cmake-modules
    - grantlee-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
rundeps    :
    - kiconthemes
    - python-pypdf2
    - python-reportlab
    - python-six
setup      : |
    %patch -p1 < $pkgfiles/fix-svg.patch
    %cmake
build      : |
    %make
install    : |
    %make_install
